### ISSUE TITLE
Login by email function does not work

### ISSUE THREAD

**Issue by Fedebirds2007** [MobilePorting/Funkin-Psych-Online-Mobile#1]
### Describe your bug here.

I just installed to give it  a try but the "Login to the network" online option does not work, I have already an account bc I normally play on pc.

### Steps to reproduce this bug.

Go to online, options and try to log in.

### Have you modded the build?

Yes, at Source Code level

### If you edited anything in this build, mention or summarize your changes.

Nope

### What is your platform?

Windows

**Comment by Fedebirds2007** [comment]
The platform is Android but It does not apear in the list

**Comment by brianass232008** [comment]
The controllers are broken On fnf online

Uploading Record_2024-09-22-20-54-33.mp4…

**Comment by mcagabe19** [comment]
update to 0.7.8

**Comment by brianass232008** [comment]
I actually update it still broke

**Comment by Fedebirds2007** [comment]
Ok i just found out the problem, I was thinking that I have to press the "A" button to confirm the email but it seems that makes nothing... I just tryed to use the enter button on the android keyboard multiple times and I succesfully loged in after a few trys

**Comment by brianass232008** [comment]
Oh thanks the game actually reset my progress I lost my awards for no reason
