### ISSUE TITLE
Failure to detect Voices.ogg

### ISSUE THREAD

**Issue by NixyARG** [MobilePorting/Funkin-Psych-Online-Mobile#1]
### Describe your bug here.

Some mods do not have a voice file to work and online psych needs the file, making it impossible to play certain mods

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
then it’s an issue with the mod, not the game

**Comment by moxie-coder** [comment]
also, in theory it should work without it, but I'll see why it's broken

**Comment by KarimAkra** [comment]
that's because some people optimize mods and put both voices and inst in one sound file
inst) deleting the voices file without disabling the "needsVoices" variable in the song json

in newer psych engine(0.7 and above) needsVoices must be disabled if you don't want to use voices file in the song or else you'll crash if it's missing

**Comment by mcagabe19** [comment]
> that's because some people optimize mods and put both voices and inst in one sound file inst) deleting the voices file without disabling the "needsVoices" variable in the song json
> 
> in newer psych engine(0.7 and above) needsVoices must be disabled if you don't want to use voices file in the song or else you'll crash if it's missing

^

**Comment by moxie-coder** [comment]
> that's because some people optimize mods and put both voices and inst in one sound file inst) deleting the voices file without disabling the "needsVoices" variable in the song json
> 
> in newer psych engine(0.7 and above) needsVoices must be disabled if you don't want to use voices file in the song or else you'll crash if it's missing

been unable to reproduce
