### ISSUE TITLE
Buttons do not work in the new version 0.7.8

### ISSUE THREAD

**Issue by BahaGH10** [MobilePorting/Funkin-Psych-Online-Mobile#2]
### Describe your bug here.

I downloaded a new version of Psych Online Mobile but for some reason after downloading the files for the engine the buttons themselves moved in the functions and some in all do not work because of this normal play is not possible

### Steps to reproduce this bug.

Download the new version of Psych Online Mobile and maybe with a BIG chance you'll have a bug like me that hasn't been fixed yet

### Have you modded the build?

Yes, at Source Code level

### What is your platform?

Not in this list (WILL BE CLOSED)

**Comment by mcagabe19** [comment]
go read the releases
