### ISSUE TITLE
Position and offsets

### ISSUE THREAD

**Issue by ShizuraFNF** [MobilePorting/Funkin-Psych-Online-Mobile#3]
### Describe your bug here.

The character positions and offsets are broken, can you fix this?

(The bug also appeared in week 6 if I'm not mistaken)

https://github.com/MobilePorting/Funkin-Psych-Online-Mobile/assets/157070808/1aa267e5-a1c6-4e60-a585-a8c6ba060df7

(ignore the delay in the song in the video)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by moxie-coder** [comment]
issue with the mods, not our problem

**Comment by ShizuraFNF** [comment]
> issue with the mods, not our problem

I don't know if week 6 is a mod because week 6 is also affected by that bug.

"issue with mods" you should know that it works on the regular Psych engine.

**Comment by moxie-coder** [comment]
> > issue with the mods, not our problem
> 
> I don't know if week 6 is a mod because week 6 is also affected by that bug.
> 
> "issue with mods" you should know that it works on the regular Psych engine.

yeah well, not every mod is gonna work here, and week 6 obviously isn't a mod, it's an issue with the mods you installed, it ain't our problem

**Comment by mcagabe19** [comment]
upstream issue report to there

**Comment by ShizuraFNF** [comment]
> > > issue with the mods, not our problem
> > 
> > 
> > I don't know if week 6 is a mod because week 6 is also affected by that bug.
> > "issue with mods" you should know that it works on the regular Psych engine.
> 
> yeah well, not every mod is gonna work here, and week 6 obviously isn't a mod, it's an issue with the mods you installed, it ain't our problem

every mod i downloaded has this bugs.
And i hate it and you should test the Mods folder before saying that because if you're still stubbornly arguing "it's not your problem it's a bug in the mods you installed"
If it's true that this is just a problem with the mod I installed and not all mods have this bug, then provide proof that not all mods have this bug by recording a video and sending it here.

**Comment by KarimAkra** [comment]
https://github.com/MobilePorting/Funkin-Psych-Online-Mobile/assets/144803230/8333cb0d-7de2-4c82-a4b3-d5f26347fad8

Are you satisfied now?
Week6 doesn't have a offset issue it's a cam position issue which isn't our fault it's from psych online so we can't do anything about it.

**Comment by KarimAkra** [comment]
I'm pretty sure this is happening to you due to the sprites being modified(optmized) cuz smth like that happened to me when i tried optimizing a sprite
