### ISSUE TITLE
Shader error mobile when open game

### ISSUE THREAD

**Issue by kiritinhokirigaya** [MobilePorting/Funkin-Psych-Online-Mobile#5]
### Describe your bug here.

Some error happen when i open the game, i really want to play in my phone Psych Online. SOMEONE HELP ME!
![Screenshot_20240927-134812](https://github.com/user-attachments/assets/2a8ad4ba-a4ff-4711-b30f-29e9acc2dcc8)
![Screenshot_20240927-134806](https://github.com/user-attachments/assets/68f85831-7d65-4fc9-a2a2-6574b34f8853)

### Steps to reproduce this bug.

You only open the game, after installed, and this happen.

### Command Prompt/Terminal logs

```bash
*in photo*
```

### Have you modded the build?

Yes, at Source Code level

### If you edited anything in this build, mention or summarize your changes.

Nothing.

### What is your platform?

Windows

**Comment by mcagabe19** [comment]
your phone's too old for gles 300, get a better phone

**Comment by kiritinhokirigaya** [comment]
"have you modded the build?" label is incorrect. In fact, i dont make never thing and this happen.

**Comment by kiritinhokirigaya** [comment]
have a version that opens in my phone?

**Comment by mcagabe19** [comment]
hmm idts, maybe we have to downgrade glsl version

**Comment by kiritinhokirigaya** [comment]
pls make this, i very like to play FNF, principally online.

**Comment by kiritinhokirigaya** [comment]
Have some version that not have GLSL or a version that this is downgraded?

**Comment by KarimAkra** [comment]
Can you tell us what phone you're using?

**Comment by kiritinhokirigaya** [comment]
ok, i (basically) am using a TV BOX to play FNF (kek).

**Comment by mcagabe19** [comment]
you need give full device info

**Comment by mcagabe19** [comment]
the fix has been released on 0.8.0
