### ISSUE TITLE
unable to download mods on chromeOS

### ISSUE THREAD

**Issue by ChickenSwimmer2020** [MobilePorting/Funkin-Psych-Online-Mobile#6]
### Describe your bug here.

When playing the android version of Psych Online on chromebook(android running device), mods when attempted to be downloaded give the "Unable To Connect EOF" error.

### Steps to reproduce this bug.

* try to download a mod on chromeOS X64 Dev Branch Version 131.0.6778.9 (official) [CHROMEOS IS BUILT ON ANDROID]

### Have you modded the build?

Yes, using Mods

### If you edited anything in this build, mention or summarize your changes.

Zero Modifications, straight download from the APK file

### What is your platform?

Android

**Comment by mcagabe19** [comment]
use crostini (linux containers) instead of crosvm (android)

**Comment by ChickenSwimmer2020** [comment]
how do i switch to crostini?

**Comment by TechnikTil** [comment]
> how do i switch to crostini?

that one terminal app lets u install linux (im a lil late)
