### ISSUE TITLE
I need help eof

### ISSUE THREAD

**Issue by Dragonfire75** [MobilePorting/Funkin-Psych-Online-Mobile#7]
### Describe your bug here.

![Screenshot_20241104-141115](https://github.com/user-attachments/assets/5df6e913-5c97-4f0c-ab7d-207b2a465ccf)

Idk bug that
I need help

### Steps to reproduce this bug.

Idk

### Have you modded the build?

Yes, using Mods

### What is your platform?

Android

**Comment by moxie-coder** [comment]
can you be more specific because I don’t see an issue

**Comment by mcagabe19** [comment]
bad internet

**Comment by Dragonfire75** [comment]
Ok
