### ISSUE TITLE
I cant do anything

### ISSUE THREAD

**Issue by FThyBlox** [MobilePorting/Funkin-Psych-Online-Mobile#9]
### Describe your bug here.

Ui buttons and arrow keys are broken

https://github.com/user-attachments/assets/bd007188-2bcd-46d1-a650-1ca74811af80

### Steps to reproduce this bug.

Just launch the game on 0.9.3

### Have you modded the build?

Yes, at Source Code level

### What is your platform?

Windows

**Comment by mcagabe19** [comment]
skill issue and fully reinstall

**Comment by FThyBlox** [comment]
Still same thing
